[package]
name = "felipeum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
felipeum_primitives = { path = "../../crates/primitives" }
felipeum_p2p = { path = "../../crates/net/p2p" }
felipeum_rpc = { path = "../../crates/net/rpc" }
felipeum_transaction_pool = { path = "../../crates/transaction-pool" }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
libp2p = { version = "0.39", features = ["tcp-tokio", "mdns"] }
tokio = { version = "1.0", features = ["io-util", "io-std", "macros", "rt", "rt-multi-thread", "sync", "time"] }
once_cell = "1.5"
log = "0.4"
pretty_env_logger = "0.4"
jsonrpsee = "0.16.2"
parking_lot = "0.12"
